version: "3.9"
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  
  api:
    build: .
    depends_on:
      - db
    ports:
      - 5002:5000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET: rahasia
    links:
    - db

volumes:
  db-data:
    driver: local
